# ----------------------------
# group nb XXX
# noma1 : name1 surname1
# noma2 : name2 surname2
# ----------------------------

all :compile

compile :
	./ozc -c *.oz

start :
	./ozengine Main.ozf

clean :
	@rm -rf GUI.ozf Input.ozf Main.ozf PlayerManager.ozf Player000name.ozf
